version: '3'

services:
  rttf_bot_db:
    image: postgres:13-alpine
    container_name: rttf_bot_db
    environment:
      POSTGRES_DB: rttf_bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - ./resources/volumes:/var/lib/postgresql
  rttf_bot_app:
    build: .
    environment:
      - TOKEN=${TOKEN}
      - DB_URL=${DB_URL}
    restart: always
#    depends_on:
#      - rttf_bot_db
