version: '3'

services:
  rttf_bot_db:
    image: postgres:13-alpine
    container_name: rttf_bot_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./resources/volumes/pg_data:/var/lib/postgresql/data
  rttf_bot_app:
    build: .
    env_file:
      - .env
    environment:
      - SERVICE_NAME=rttf_bot_app
    restart: always
  rttf_bot_cron:
    build: .
    env_file:
      - .env
    environment:
      - SERVICE_NAME=rttf_bot_cron
    restart: always
    command: ["cron", "-f"]
